// keep {} where you wan to skip the column
module.exports = [
  { key: "name", value: "Name" },
  { key: "calcs", value: "Calcs" },
  {},
  {},
  { key: "user1", value: "User" },
  { key: "name1", header: "Name" },
  { key: "type1", header: "Type" },
  { key: "value1", header: "Value" },
  { key: "dop1", header: "Dop" },
  { key: "client_id1", header: "Cid" },
  { key: "weight1", header: "Weight" },
  { key: "myShare1", header: "My Share" },
  { key: "youShare1", header: "You Share" },
  {},
  {},
  {},
  {},
  { key: "user2", value: "User" },
  { key: "name2", header: "Name" },
  { key: "type2", header: "Type" },
  { key: "value2", header: "Value" },
  { key: "dop2", header: "Dop" },
  { key: "client_id2", header: "Cid" },
  { key: "weight2", header: "Weight" },
  { key: "myShare2", header: "My Share" },
  { key: "youShare2", header: "You Share" },
  {},
  {},
  { key: "user1purchase", value: "User" },
  { key: "name1purchase", header: "Name" },
  { key: "type1purchase", header: "Type" },
  { key: "month1", header: "Month" },
  { key: "value1purchase", header: "Value" },
  {},
  { key: "user2purchase", value: "User" },
  { key: "name2purchase", header: "Name" },
  { key: "type2purchase", header: "Type" },
  { key: "month2", header: "Month" },
  { key: "value2purchase", header: "Value" },
];
